apiVersion: v1
entries:
  python-demo:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-02-13T16:25:42.976667267-05:00"
    description: A Helm chart for Kubernetes
    digest: 393c0ac87abe65e1329cb63ee4e7fc1252316cd7dc8d748ec682064f76fea731
    name: python-demo
    type: application
    urls:
    - https://raw.githubusercontent.com/abryson-redhat/springboot-demo/springboot-demo/gh-pages/python-demo-0.1.0.tgz
    version: 0.1.0
generated: "2024-02-13T16:25:42.9764406-05:00"
