apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-db
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
