apiVersion: v1
data:
  schema_drop.sql: RFJPUCBUQUJMRSBJRiBFWElTVFMgb3duZXJzCkNBU0NBREU7CkRST1AgVEFCTEUgSUYgRVhJU1RTIHBldHMKQ0FTQ0FERTsKRFJPUCBUQUJMRSBJRiBFWElTVFMgc3BlY2lhbHRpZXMKQ0FTQ0FERTsKRFJPUCBUQUJMRSBJRiBFWElTVFMgdHlwZXMKQ0FTQ0FERTsKRFJPUCBUQUJMRSBJRiBFWElTVFMgdmV0X3NwZWNpYWx0aWVzCkNBU0NBREU7CkRST1AgVEFCTEUgSUYgRVhJU1RTIHZldHMKQ0FTQ0FERTsKRFJPUCBUQUJMRSBJRiBFWElTVFMgdmlzaXRzCkNBU0NBREU7Cg==
  user.sql: Q1JFQVRFIFJPTEUgcGV0Y2xpbmljOwpBTFRFUiBST0xFIHBldGNsaW5pYyBXSVRIIExPR0lOOwpDUkVBVEUgREFUQUJBU0UgcGV0Y2xpbmljOwpHUkFOVCBBTEwgUFJJVklMRUdFUyBPTiBEQVRBQkFTRSBwZXRjbGluaWMgVE8gcGV0Y2xpbmljOwo=
kind: Secret
metadata:
  name: init-db-secret
  namespace: appteam1-demo-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
